services:
  webapp:
    build: .
    env_file: .env
    environment:
      - PGUSER=${PGUSER:-totoro}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-26257}
      - PGDATABASE=${PGDATABASE:-mydb}
    ports:
      - 80:8080
    depends_on:
      - db
    container_name: webapp
    hostname: webapp
    networks:
      - back-tier

  db:
    image: cockroachdb/cockroach:latest-v20.1
    container_name: db
    hostname: db
    networks:
      - back-tier
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - db-data:/cockroach/cockroach-data
    command: start-single-node --insecure

networks:
  back-tier:

volumes:
  db-data:
